# Generated by Django 5.2.4 on 2025-07-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="E-mail")),
                ("full_name", models.CharField(max_length=255, verbose_name="Ф. И. О.")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки "),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")],
                        default="Создана",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailings.message", verbose_name="Сообщение "
                    ),
                ),
                ("recipients", models.ManyToManyField(to="mailings.recipient", verbose_name="Получатели")),
            ],
        ),
        migrations.CreateModel(
            name="SendAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailings.campaign", verbose_name="Рассылка"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SendLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")], max_length=10),
                ),
                ("server_response", models.TextField()),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailings.campaign")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailings.recipient")),
            ],
        ),
    ]
