# Generated by Django 5.2.4 on 2025-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Текст письма"),
        ),
    ]
