# Generated by Django 5.2.4 on 2025-07-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_message_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailings.message", verbose_name="Сообщение"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время первой отправки"),
        ),
    ]
