# Generated by Django 5.2.4 on 2025-07-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_campaign_end_time_alter_campaign_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
        ),
    ]
