# Generated by Django 5.2.4 on 2025-07-22 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_campaign_end_time_alter_campaign_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_time",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now, verbose_name="Дата и время окончания отправки"
            ),
            preserve_default=False,
        ),
    ]
