# Generated by Django 5.2.4 on 2025-07-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_campaign_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "permissions": [("can_finish_campaign", "Can finish campaign")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
        migrations.AlterModelOptions(
            name="sendattempt",
            options={"verbose_name": "Отправка", "verbose_name_plural": "Отправки"},
        ),
        migrations.AlterModelOptions(
            name="sendlog",
            options={"verbose_name": "Лог", "verbose_name_plural": "Логи"},
        ),
    ]
